/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.City;
import model.Country;
import model.Countrylanguage;
import model.HibernateUtil;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;


/**
 *
 * @author Gabriel
 */
public class SearchScreen extends javax.swing.JFrame {

    /**
     * Creates new form SearchScreen
     */
    public SearchScreen() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchLangButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchCountryButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchCityButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchLangButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchLangButton.setText("PESQUISAR");
        searchLangButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLangButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 50, 88));
        jLabel1.setText("PESQUISAR TODAS LÍNGUAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 50, 88));
        jLabel2.setText("PESQUISAR TODOS PAÍSES");

        searchCountryButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchCountryButton.setText("PESQUISAR");
        searchCountryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchCountryButtonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 50, 88));
        jLabel3.setText("PESQUISAR TODAS CIDADES");

        searchCityButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchCityButton.setText("PESQUISAR");
        searchCityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchCityButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(searchLangButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(searchCountryButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(searchCityButton)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(searchLangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchCountryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(searchCityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchLangButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLangButtonMouseClicked
        // TODO add your handling code here:
        
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tr = null;
        tr = session.beginTransaction();
        String hql = "From Countrylanguage";
        Query query = session.createQuery(hql);
        List<Countrylanguage> list = query.list();
        Iterator iter = list.iterator();
        
        String result = "--------- TODAS AS LÍNGUAS REGISTRADAS: --------- \n\n";
        result += "LÍNGUA -------- PÁIS ------------ É OFICIAL ---------- (%) \n\n";
        for (int i=0; i<list.size();i++){
            result +=  list.get(i).getId().getLanguage()+"\t" + list.get(i).getId().getCountrycode() + "\t"+ list.get(i).isIsofficial()+ "\t"+ list.get(i).getPercentage() +"\n";
        }
        JTextArea textArea = new JTextArea(result);
        JScrollPane scrollPane = new JScrollPane(textArea);  
        textArea.setLineWrap(true);  
        textArea.setWrapStyleWord(true); 
        scrollPane.setPreferredSize( new Dimension( 500, 500 ) );
        JOptionPane.showMessageDialog(null, scrollPane, "PESQUISA DE LÍNGUAS",  
                                       JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_searchLangButtonMouseClicked

    private void searchCountryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCountryButtonMouseClicked
        // TODO add your handling code here:
                Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tr = null;
        tr = session.beginTransaction();
        String hql = "From Country";
        Query query = session.createQuery(hql);
        List<Country> list = query.list();
        Iterator iter = list.iterator();
        
                String result = "--------- TODOS OS PAÍSES REGISTRADAS: --------- \n\n";
        result += "NOME, CONTINENTE, POPULAÇÃO, EXPECTATIVA DE VIDA, FORMA DE GOVERNO, CHEFE DE ESTADO\n\n";
        for (int i=0; i<list.size();i++){
            result += list.get(i).getName() + "\t\t" + list.get(i).getContinent() + "\t" + list.get(i).getPopulation() + "\t\t" + list.get(i).getLifeexpectancy() + "\t" + list.get(i).getGovernmentform() + "\t\t" + list.get(i).getHeadofstate() + "\n";
        }
        JTextArea textArea = new JTextArea(result);
        JScrollPane scrollPane = new JScrollPane(textArea);  
        textArea.setLineWrap(true);  
        textArea.setWrapStyleWord(true); 
        scrollPane.setPreferredSize( new Dimension( 1500, 500 ) );
        JOptionPane.showMessageDialog(null, scrollPane, "PESQUISA DE PAÍSES",  
                                       JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_searchCountryButtonMouseClicked

    private void searchCityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCityButtonMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
                Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tr = null;
        tr = session.beginTransaction();
        String hql = "From City";
        Query query = session.createQuery(hql);
        List<City> list = query.list();
        Iterator iter = list.iterator();
        
        String result = "--------- TODAS AS CIDADES REGISTRADAS: --------- \n\n";
        result += "POPULAÇÃO \t NOME \t PAÍS \t DISTRITO\n\n";
        for (int i=0; i<list.size();i++){
            result += list.get(i).getPopulation() + "\t" + list.get(i).getName() + "\t" + list.get(i).getCountrycode() + "\t" + list.get(i).getDistrict() + "\n";
        }
        JTextArea textArea = new JTextArea(result);
        JScrollPane scrollPane = new JScrollPane(textArea);  
        textArea.setLineWrap(true);  
        textArea.setWrapStyleWord(true); 
        scrollPane.setPreferredSize( new Dimension( 500, 500 ) );
        JOptionPane.showMessageDialog(null, scrollPane, "PESQUISA DE CIDADES",  
                                       JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_searchCityButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchCityButton;
    private javax.swing.JButton searchCountryButton;
    private javax.swing.JButton searchLangButton;
    // End of variables declaration//GEN-END:variables
}
